// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuuI8RMk4pPsUF446VkbLHybZFlDo3Aj8',
    appId: '1:676923374257:web:2f009f4afbace2b5454090',
    messagingSenderId: '676923374257',
    projectId: 'facerecogauth01',
    authDomain: 'facerecogauth01.firebaseapp.com',
    databaseURL: 'https://facerecogauth01-default-rtdb.firebaseio.com',
    storageBucket: 'facerecogauth01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN4LCzL9IDvxLdV7Dq1FXGqjTVpqobDSg',
    appId: '1:676923374257:android:427dd7c6e28a6947454090',
    messagingSenderId: '676923374257',
    projectId: 'facerecogauth01',
    databaseURL: 'https://facerecogauth01-default-rtdb.firebaseio.com',
    storageBucket: 'facerecogauth01.appspot.com',
  );
}
